# Generated by Django 4.2 on 2023-04-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemaniacs', '0004_remove_playlist_movie_playlist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='list_type',
            field=models.CharField(default='c', max_length=1),
        ),
    ]
