# Generated by Django 4.2 on 2023-04-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviemaniacs', '0005_playlist_list_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
