# Generated by Django 4.2 on 2023-05-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemaniacs', '0008_review_username_alter_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
